### ISSUE TITLE
Trying to reach out to you.

### ISSUE THREAD

**Issue by richyk1** [primislas/oikoumene#79]
Hi man, I'm doing a similar project and I'd like to discuss some things. If you use Discord add me (koolkid#5348), otherwise I'll respond here.

**Comment by primislas** [comment]
Hey. It's already late here, I was just wrapping up the day's work and noticed the issue. I'll get in touch with you on Discord on Sunday. Should add contacts to readme, I guess I never expected anyone to try to contact me. :)

**Comment by primislas** [comment]
Added contact information to project's front page.
